20260830.1 gperon global branch merge

diff --git a/graphics/meshlab/meshlab.SlackBuild b/graphics/meshlab/meshlab.SlackBuild
--- a/graphics/meshlab/meshlab.SlackBuild
+++ b/graphics/meshlab/meshlab.SlackBuild
@@ -31,9 +31,8 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=meshlab
-SRCNAM=Meshlab
-VCGLIB=vcglib
-VERSION=${VERSION:-2021.10}
+SRCNAM=MeshLab
+VERSION=${VERSION:-2025.07}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -59,10 +58,8 @@ if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
 else
   LIBDIRSUFFIX=""
@@ -74,32 +71,62 @@ rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 
-FILENAME=$PRGNAM-$SRCNAM-$VERSION
+rm -rf $PRGNAM-$VERSION
+tar xvf $CWD/$PRGNAM-$SRCNAM-$VERSION.tar.gz --transform="s#$SRCNAM-$VERSION/#$VERSION/#"
+cd $PRGNAM-$VERSION/src
+tar xvf $CWD/vcglib-$VERSION.tar.gz --transform="s#vcglib-$VERSION/#vcglib/#"
+cd -
 
-rm -rf $FILENAME
-tar xvf $CWD/$FILENAME.tar.gz
-cd $FILENAME/src
-tar xvf $CWD/$VCGLIB-$VERSION.tar.gz --transform="s#$VCGLIB-$VERSION/#$VCGLIB/#"
-cd ..
-chown -R root:root .
-find -L . \
+# there are a lot of libraries to download from the script, let's download some of them 
+mkdir $PRGNAM-$VERSION/{build,src/external/downloads}
+cd $PRGNAM-$VERSION/src/external/downloads 
+tar xvf $CWD/nexus-2025.05.tar.gz
+cd -
+cd $PRGNAM-$VERSION/src/external/downloads/nexus-2025.05/src
+tar xvf $CWD/corto-$VERSION.tar.gz --transform="s#corto-$VERSION/#corto/#"
+cd -
+cd $PRGNAM-$VERSION/src/external/downloads 
+tar xvf $CWD/libE57Format-3.1.1.tar.gz
+cd -
+
+chown -R root:root $PRGNAM-$VERSION
+find -L $PRGNAM-$VERSION \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \+ -o \
+  -o -perm 511 \) -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-mkdir -p build
+cd $PRGNAM-$VERSION
+patch -p1 < $CWD/lib3mf.patch
+patch --binary -p1 < $CWD/libE57Format-cmake-cmp0153.patch
+# Force a minimum required version at the top of the failing plugin file
+find . -name "CMakeLists.txt" | while read -r cfile; do
+    if ! grep -q "cmake_minimum_required" "$cfile"; then
+        # Use sed to add it to the very first line
+        sed -i '1i cmake_minimum_required(VERSION 4.3)' "$cfile"
+    fi
+done
+
 cmake \
   -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
   -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
-  -DALLOW_SYSTEM_QHULL=OFF \
   -DCMAKE_INSTALL_PREFIX=/usr \
+  -DMESHLAB_LIB_INSTALL_DIR=lib$LIBDIRSUFFIX \
+  -DMESHLAB_PLUGIN_INSTALL_DIR=lib$LIBDIRSUFFIX/$PRGNAM/plugins \
+  -DCMAKE_INSTALL_DATAROOTDIR=share \
+  -DCMAKE_POLICY_DEFAULT_CMP0153=OLD \
+  -DCMAKE_BUILD_TYPE=Release \
+  -DCMAKE_POLICY_VERSION_MINIMUM=4.3 \
   -G Ninja \
   -B ./build \
   -S ./src
-# shellcheck disable=SC2046 # allow MAKEFLAGS to split when passing multiple flags.
-DESTDIR=$PKG "${NINJA:=ninja}" $(grep -oP -- '-+[A-z]+ ?[0-9]*'<<<"${MAKEFLAGS:--j1}") -C "./build" install
+ninja -C "./build"
+DESTDIR="$PKG" ninja -C "./build" install
 
+# fix resources folder
+mkdir -p $PKG/usr/share/$PRGNAM
+mv $PKG/*{frag,gdp,vert} $PKG/usr/share/$PRGNAM/
+mv $PKG/{decorate_shadow,splatpyramid} $PKG/usr/share/$PRGNAM/
 # fix plugin folder
 if [ $LIBDIRSUFFIX ] ; then
   mkdir -p $PKG/usr/lib/$PRGNAM
@@ -111,7 +138,6 @@ fi
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-# Install and compress man pages
 mkdir -p $PKG/usr/man/man1
 cp docs/man/$PRGNAM.1 $PKG/usr/man/man1/
 if [ -d $PKG/usr/man ]; then
@@ -120,11 +146,6 @@ if [ -d $PKG/usr/man ]; then
   for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
   ) 
 fi
-
-# fix version in desktop entry
-#sed -i "s#Version=.*#Version=$VERSION#" $PKG/usr/share/applications/$PRGNAM.desktop
-# 20220227 bkw: wrong. Version in a .desktop file is the version of the
-# desktop file specification (usually 1.0), not the version of the application.
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a \
